services:
  - type: web
    name: bilagh-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: python startup_download_models.py && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        sync: false # set manually in Render dashboard
      - key: SECRET_KEY
        sync: false # set manually in Render dashboard
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: CLOUDINARY_CLOUD_NAME
        value: dtiji2s4k
      - key: CLOUDINARY_API_KEY
        sync: false # set manually
      - key: CLOUDINARY_API_SECRET
        sync: false # set manually
      - key: KERAS_MODEL_URL
        sync: false # paste the public URL to your .keras file here
